{% set name = "adios4dolfinx" %}
{% set version = "0.9.0" %}
{% set major_minor = version.rsplit(".", 1)[0] %}

package:
  name: adios4dolfinx
  version: {{ version }}

source:
  url: https://github.com/jorgensd/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5a72a8bc111d848b56d6eb776d7ca5963fe41e4126a3d875304224f80f15b8f6

build:
  number: 0
  noarch: python

  # openmpi oversubscribe env
  script_env:
    - MPIEXEC_TIMEOUT=400

  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - fenics-dolfinx {{ major_minor }}
    - adios2 * mpi_*
    - numpy >=1.21
    - python >=3.9
    - mpi4py

test:
  source_files:
    - pyproject.toml
    - tests
  requires:
    - pip
    - ipyparallel
    - pytest
  commands:
    - pytest -vs tests
    - mpirun -n 2 pytest tests
    - pip check

about:
  home: https://github.com/jorgensd/adios4dolfinx
  summary: Checkpointing for DOLFINx
  description: |
    This library contains an add-on to FEniCSx enabling the checkpointing meshes and solutions from DOLFINx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://jorgensd.github.io/adios4dolfinx/
  dev_url: https://github.com/jorgensd/adios4dolfinx/

extra:
  feedstock-name: adios4dolfinx
  recipe-maintainers:
    - jorgensd
    - minrk
