{% set name = "adios4dolfinx" %}
{% set version = "0.9.4" %}
{% set major_minor = version.rsplit(".", 1)[0] %}
{% set post = ".post0" %}

package:
  name: adios4dolfinx
  version: {{ version }}

source:
  url: https://github.com/jorgensd/{{ name }}/archive/refs/tags/v{{ version }}{{ post }}.tar.gz
  sha256: 1d75d4f45f28c64821ad023df3273d933f1d4752c0e53b62f41030dca06bd627

build:
  number: 0
  noarch: python

  # openmpi oversubscribe env
  script_env:
    - MPIEXEC_TIMEOUT=400

  script: python -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - fenics-dolfinx {{ major_minor }}
    - adios2  >=2.10.2 mpi_*
    - numpy >=1.21
    - python >={{ python_min }}
    - mpi4py

test:
  source_files:
    - pyproject.toml
    - tests
  requires:
    - pip
    - ipyparallel
    - mpich  # avoid openmpi MPIEXEC_TIMEOUT bug
    - pytest
    - python {{ python_min }}
  commands:
    - pytest --log-cli-level=debug -vvs --maxfail 4 tests
    - mpiexec -n 2 pytest --log-cli-level=debug -vvs --maxfail 4 tests
    - pip check

about:
  home: https://github.com/jorgensd/adios4dolfinx
  summary: Checkpointing for DOLFINx
  description: |
    This library contains an add-on to FEniCSx enabling the checkpointing meshes and solutions from DOLFINx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://jorgensd.github.io/adios4dolfinx/
  dev_url: https://github.com/jorgensd/adios4dolfinx/

extra:
  feedstock-name: adios4dolfinx
  recipe-maintainers:
    - jorgensd
    - minrk
